site_name: YaCy Docs
site_author: Michael Christen
site_description: "YaCy P2P - Decentralized Search Engine"
site_url: "https://yacy.net/"
repo_url: "https://github.com/yacy/yacy_net_homepage.git"
use_directory_urls: false

theme:
    name: readthedocs
//    custom_dir: 'cinder-superhero'

nav:
  - Docs: docs.md
  - FAQ: faq.md

markdown_extensions:
  - admonition
  - attr_list
