name: CI Script to build YaCy Home Page on self-hosted server

on: push

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - run: pip install --break-system-packages mkdocs
    - run: mkdocs build
